# Generated by Django 4.2.6 on 2024-02-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0002_userattribute_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
