# Generated by Django 4.2.6 on 2024-02-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0003_userattribute_new_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattribute',
            name='fullname',
        ),
        migrations.AddField(
            model_name='userattribute',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
    ]
