# Generated by Django 4.2.6 on 2024-02-19 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0004_remove_userattribute_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='friends',
            field=models.ManyToManyField(blank=True, to='stressapp.userattribute'),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='profile_picture',
            field=models.ImageField(default='default_profpic.png', upload_to=''),
        ),
        migrations.CreateModel(
            name='friend_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to='stressapp.userattribute')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to='stressapp.userattribute')),
            ],
        ),
    ]
