# Generated by Django 4.2.6 on 2024-02-20 01:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0005_userattribute_friends_userattribute_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='stressapp.userattribute')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames_id', models.CharField(max_length=160)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('chat_messages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='stressapp.message')),
                ('participants', models.ManyToManyField(related_name='participants', to='stressapp.userattribute')),
            ],
        ),
    ]
