# Generated by Django 4.2.6 on 2024-02-20 04:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0006_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='usernames_id',
        ),
        migrations.AddField(
            model_name='userattribute',
            name='chats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='stressapp.chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
