# Generated by Django 4.2.6 on 2024-02-21 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0007_remove_chat_usernames_id_userattribute_chats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='stressapp.message'),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to='stressapp.userattribute'),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to='stressapp.userattribute'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='stressapp.userattribute'),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='chats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='stressapp.chat'),
        ),
    ]
