# Generated by Django 4.2.6 on 2024-02-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0008_alter_chat_chat_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_request',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='userattribute',
            name='chats',
        ),
        migrations.AddField(
            model_name='friend_request',
            name='to_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='to_user', to='stressapp.userattribute'),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, related_name='chats', to='stressapp.chat'),
        ),
    ]
