# Generated by Django 4.2.6 on 2024-02-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0011_remove_chat_chat_messages_chat_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
